# Generated by Django 4.2.2 on 2023-07-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_commentpost_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content_img",
            field=models.ImageField(null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content_vid",
            field=models.FileField(null=True, upload_to="videos"),
        ),
    ]
