# Generated by Django 4.2.2 on 2023-07-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_alter_post_content_img_alter_post_content_vid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content_img",
            field=models.ImageField(
                default="images/d4c602d1d4891bd7309ce73f1cd5bea1.jpg",
                upload_to="images",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content_vid",
            field=models.FileField(
                default="videos/910f499a76b1c0bc1e0f7bd0067fc2e6.jpg",
                upload_to="videos",
            ),
        ),
    ]
