# Generated by Django 4.2.2 on 2023-07-18 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0003_remove_comment_reply_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="back_img",
            field=models.ImageField(
                blank=True, default="images/597_1.jpg", upload_to="images"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GR", "General"),
                    ("LS", "LifeStyle"),
                    ("TR", "Travel"),
                    ("DS", "Design"),
                    ("CR", "Creative"),
                    ("ED", "Education"),
                ],
                default="GR",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="pub_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 7, 18, 15, 29, 37, 843156)
            ),
        ),
    ]
