# Generated by Django 4.2.2 on 2023-07-18 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0004_alter_blog_back_img_alter_blog_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="pub_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 7, 18, 15, 50, 31, 287745, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
